name: networker_s5
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/networker/networker
      ref: e71ccebf4152189b0d1c2656e4e5294d5f927163
  s5: ^0.2.0
  hive: ^2.2.3
  http: ^1.2.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.9
