name: networker_s5
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.8.0
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 54d35ef572172ac74d853d47af0140a89b36d714
  s5: ^0.2.0
  hive: ^2.2.3
  http: ^1.2.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9
