name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.8.0
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 54d35ef572172ac74d853d47af0140a89b36d714
  flutter_webrtc: ^0.12.1+hotfix.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9
