name: networker
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
