name: lw_file_system
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.1
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  idb_shim: ^2.4.1+1
  rxdart: ^0.28.0
  flutter_secure_storage: ^9.2.2
  web: ">=0.5.1 <2.0.0"
  path: ^1.9.0
  xml: ^6.5.0
  lw_file_system_api:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/lw_file_system_api
      ref: 374e69598cf1b10fcdf8cb9989606e7e307b3a23
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.10
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^5.0.0
