name: lw_file_system
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.1
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  idb_shim: ^2.4.1+1
  rxdart: ^0.28.0
  flutter_secure_storage: ">=9.2.2 <11.0.0"
  web: ">=0.5.1 <2.0.0"
  path: ^1.9.0
  xml: ^6.5.0
  lw_file_system_api:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/lw_file_system_api
      ref: 05c726ca745112dec80c6d30a27478e1556367b7
  async: ^2.12.0
  synchronized: ^3.4.0
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.4.0
  flutter_lints: ^6.0.0
