name: localizer
description: Simple to use dart package to localize your app.
version: 1.0.1+1
homepage: https://github.com/LinwoodCloud/dart_pkgs
repository: https://github.com/LinwoodCloud/dart_pkgs
documentation: https://github.com/LinwoodCloud/dart_pkgs
issue_tracker: https://github.com/LinwoodCloud/dart_pkgs/issues

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
dependencies: 
  meta: ^1.7.0
  sprintf: ^7.0.0
  yaml: ^3.1.1
