name: lw_file_system_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  dart_mappable: ^4.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dart_mappable_builder: ^4.2.3
  build_runner: ^2.4.11
